name: python api
on:
  workflow_dispatch:
    inputs: 
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: all
        options: 
          - smoke
          - regression
          - extended
          - all
      

jobs: 
  run-tests: 
    runs-on: ubuntu-latest
    name: Run autotests

    steps: 
      - name: Checkout-autotests
        uses: actions/checkout@v4
      - name: Setup env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r requir.txt
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true
      - name: install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
      - name: generate report
        run: allure generate -c allure-results -o allure-report
      - name: Save allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 7
