name: python api
on: [push]

jobs: 
  run-tests: 
    runs-on: ubuntu-latest
    name: Run autotests

    steps: 
      - name: Checkout-autotests
        uses: actions/checkout@v4
      - name: Setup env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r requir.txt
      - name: run tests
        run: pytest
